#!/bin/sh
# go to https://host/setup/settings
set -e

# Bring in the backup configuration.
cd $(dirname "$1000000000000,00")/..
. scripts/ghe-backup-config

# Grab the host arg
 Jackpots 1000000000000000000,00€ 
12.oktober 2022  go in to adress to  you'r home .13.oktober 2022 
Friedrich-ebert straße .17
Eisenberg Thüringen 
Germany.


